// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa3K-kfbeBApN9S4g3e5axCu-FJ5j2S00',
    appId: '1:760418303988:web:a85f015b5c74d7494b03a1',
    messagingSenderId: '760418303988',
    projectId: 'trendora-ai-2026',
    authDomain: 'trendora-ai-2026.firebaseapp.com',
    storageBucket: 'trendora-ai-2026.firebasestorage.app',
    measurementId: 'G-WJDDES5TG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRc58TLMDguz-AVNQLU4EV53klPU0yxP4',
    appId: '1:760418303988:android:4892c83c26e2b80e4b03a1',
    messagingSenderId: '760418303988',
    projectId: 'trendora-ai-2026',
    storageBucket: 'trendora-ai-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0nphVpH7jOjZpo64gP8UR2Uu5b6vP1Bc',
    appId: '1:760418303988:ios:7f0f9cb85c17ba1b4b03a1',
    messagingSenderId: '760418303988',
    projectId: 'trendora-ai-2026',
    storageBucket: 'trendora-ai-2026.firebasestorage.app',
    iosBundleId: 'com.example.trendora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0nphVpH7jOjZpo64gP8UR2Uu5b6vP1Bc',
    appId: '1:760418303988:ios:7f0f9cb85c17ba1b4b03a1',
    messagingSenderId: '760418303988',
    projectId: 'trendora-ai-2026',
    storageBucket: 'trendora-ai-2026.firebasestorage.app',
    iosBundleId: 'com.example.trendora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa3K-kfbeBApN9S4g3e5axCu-FJ5j2S00',
    appId: '1:760418303988:web:2b1b72e7098a52874b03a1',
    messagingSenderId: '760418303988',
    projectId: 'trendora-ai-2026',
    authDomain: 'trendora-ai-2026.firebaseapp.com',
    storageBucket: 'trendora-ai-2026.firebasestorage.app',
    measurementId: 'G-5X3ST0ML01',
  );
}
